{% set name = "pdm-pep517" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-pep517-{{ version }}.tar.gz
  sha256: a4407703d50fa4d671383a354868b05a13060c1bf38264cbb5ddc9a73e4a1dc5

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python

test:
  imports:
    - pdm.pep517
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm-pep517/
  dev_url: https://github.com/pdm-project/pdm-pep517
  doc_url: https://github.com/pdm-project/pdm-pep517/blob/master/README.md
  summary: A PEP 517 backend for PDM that supports PEP 621 metadata
  description: |
    This is the backend for PDM projects, but you can also
    use it alone. It reads the metadata of PEP 621 format and
    converts it to Core metadata.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
