{% set name = "pdm-pep517" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-pep517-{{ version }}.tar.gz
  sha256: 74ece9694c4ff5f903fba000ec43f075143872c41248daccecf7464f98ce680c

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python

test:
  imports:
    - pdm.pep517
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm-pep517/
  dev_url: https://github.com/pdm-project/pdm-pep517
  doc_url: https://github.com/pdm-project/pdm-pep517/blob/master/README.md
  summary: A PEP 517 backend for PDM that supports PEP 621 metadata
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
