{% set name = "pdm-pep517" %}
{% set version = "0.12.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-pep517-{{ version }}.tar.gz
  sha256: e918b7b3850f42cbbf5a6b71e75d43c3dca0be624c25e59dfda5bb6224a20e7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pdm.pep517
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm-pep517/
  summary: A PEP 517 backend for PDM that supports PEP 621 metadata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
